### ISSUE TITLE
User Popouts Aren't Rounded

### ISSUE THREAD

**Issue by zydezu** [MarkChan0225/RoundedDiscord#10]
![2024-06-08_05-52-19_999_Discord](https://github.com/MarkChan0225/RoundedDiscord/assets/50119098/154a60c8-161b-426b-85b4-dd55a2c816c1)
User popouts are square...

I've found that adding the following css fixes this:
```css
/* make user pop outs rounded */
.userProfileOuterUnthemed__9741c {
  --profile-gradient-secondary-color: none !important;
  border-radius: 16px;
}

.userProfileOuterThemed_a425f3 {
  border-radius: 16px;
}

.bannerSVGWrapper__8a38c:not(:has([style*=image])) [style*=background-color] {
  border-radius: 16px 16px 0 0;
}

.userPopoutOverlayBackground__3e7e6 {
  border-radius: 16px !important;
}
```
![2024-06-08_05-53-22_463_Discord](https://github.com/MarkChan0225/RoundedDiscord/assets/50119098/1f46511d-efe4-4ba7-b283-f21ff9be4758)
